export const erroresDecidir:any = []
erroresDecidir['invalid_request_error-invalid_param-card_number'] = { desc: 'No se completó el numero de la tarjeta' };
erroresDecidir['invalid_request_error-invalid_param-card_expiration_month'] = { desc: 'No se completó el mes de vencimiento de la tarjeta' };
erroresDecidir['invalid_request_error-invalid_param-card_expiration_year'] = { desc: 'No se completó el año de vencimiento de la tarjeta' };
erroresDecidir['invalid_request_error-invalid_param-card_holder_name'] = { desc: 'No se completó el nomobre del propietario de la tarjeta' };
erroresDecidir['invalid_request_error-invalid_param-payment_method_id'] = { desc: 'El Metodo de pago no coincide con el de la tarjeta' };
erroresDecidir['invalid_request_error-cardData-expired card'] = { desc: 'La tarjeta con la que estas intentando pagar esta vencida' };
erroresDecidir['invalid_request_error-invalid_param-bin'] = { desc: 'Numero de tarjeta erroneo' };

export const erroresRechazoDecidir:any = []
erroresRechazoDecidir[1] = { descCorta: 'PEDIR AUTORIZACION', desc: 'Solicitar autorización telefónica, en caso de ser aprobada, cargar el código obtenido y dejar la operación en OFFLINE.'};
erroresRechazoDecidir[2] = { descCorta: 'PEDIR AUTORIZACION', desc: 'Solicitar autorización telefónica, en caso de ser aprobada, cargar el código obtenido y dejar la operación en OFFLINE.'};
erroresRechazoDecidir[3] = { descCorta: 'COMERCIO INVALIDO', desc: 'Verificar parámetros del sistema, código de comercio mal cargado'};
erroresRechazoDecidir[4] = { descCorta: 'CAPTURAR TARJETA', desc: 'Denegada, capturar la tarjeta.'};
erroresRechazoDecidir[5] = { descCorta: 'DENEGADA', desc: 'Denegada'};
erroresRechazoDecidir[7] = { descCorta: 'RETENGA Y LLAME', desc: 'Denegada, llamar al Centro de Autorizaciones.'};
erroresRechazoDecidir[8] = { descCorta: 'INGRESO MANUAL INCORRECTO', desc: 'ingreso manual incorrecto'};
erroresRechazoDecidir[12] = { descCorta: 'TRANSAC. INVALIDA', desc: 'Verificar el sistema, transacción no reconocida en el sistema.'};
erroresRechazoDecidir[13] = { descCorta: 'MONTO INVALIDO', desc: 'Verificar el sistema, error en el formato del campo importe'};
erroresRechazoDecidir[14] = { descCorta: 'TARJETA INVALIDA', desc: 'Denegada, tarjeta no corresponde.'};
erroresRechazoDecidir[19] = { descCorta: 'AUTO APPROVE IN RECEIVEPAYMENT', desc: 'Auto approve in ReceivePayment.'};
erroresRechazoDecidir[25] = { descCorta: 'NO EXISTE ORIGINAL', desc: 'Denegada, registro no encontrado en el archivo de transacciones.'};
erroresRechazoDecidir[28] = { descCorta: 'SERVICIO NO DISPONIBLE', desc: 'Momentáneamente el servicio no está disponible. Se debe reintentar en unos segundos.'};
erroresRechazoDecidir[30] = { descCorta: 'ERROR EN FORMATO', desc: 'Verificar el sistema, error en el formato del mensaje.'};
erroresRechazoDecidir[31] = { descCorta: 'THE PARAMETER MUST BE SPECIFIED.', desc: 'The parameter must be specified when another'};
erroresRechazoDecidir[38] = { descCorta: 'EXCEDE ING.DE PIN', desc: 'Denegada, excede cantidad de reintentos de PIN'};
erroresRechazoDecidir[39] = { descCorta: 'INGRESO MANUAL INCORRECTO', desc: 'Ingreso manual incorrecto'};
erroresRechazoDecidir[43] = { descCorta: 'RETENER TARJETA', desc: 'Denegada, retener tarjeta'};
erroresRechazoDecidir[45] = { descCorta: 'NO OPERA EN CUOTAS', desc: 'Denegada, tarjeta inhibida para operar en cuotas'};
erroresRechazoDecidir[46] = { descCorta: 'TARJETA NO VIGENTE', desc: 'Denegada, tarjeta no está vigente aún'};
erroresRechazoDecidir[47] = { descCorta: 'PIN REQUERIDO', desc: 'Denegada, tarjeta requiere ingreso de PIN.'};
erroresRechazoDecidir[48] = { descCorta: 'EXCEDE MAX. CUOTAS', desc: 'Denegada, excede cantidad máxima de cuotas permitida.'};
erroresRechazoDecidir[49] = { descCorta: 'ERROR FECHA VENCIM.', desc: 'Verificar el sistema, error en formato de fecha de expiración (vto)'};
erroresRechazoDecidir[50] = { descCorta: 'ENTREGA SUPERA LIMITE', desc: 'Entrega supera limite'};
erroresRechazoDecidir[51] = { descCorta: 'FONDOS INSUFICIENTES', desc: 'Denegada, no posee fondos suficientes.'};
erroresRechazoDecidir[53] = { descCorta: 'CUENTA INEXISTENTE', desc: 'Denegada, no existe cuenta asociada.'};
erroresRechazoDecidir[54] = { descCorta: 'TARJETA VENCIDA', desc: 'Denegada, tarjeta expirada.'};
erroresRechazoDecidir[55] = { descCorta: 'PIN INCORRECTO', desc: 'Denegada, código de identificación personal es incorrecto.'};
erroresRechazoDecidir[56] = { descCorta: 'TARJ. NO HABILITADA', desc: 'Denegada, emisor no habilitado en el sistema.'};
erroresRechazoDecidir[57] = { descCorta: 'TRANS. NO PERMITIDA', desc: 'Verificar el sistema, transacción no permitida a dicha tarjeta.'};
erroresRechazoDecidir[58] = { descCorta: 'SERVICIO INVALIDO', desc: 'Verificar el sistema, transacción no permitida a dicha terminal.'};
erroresRechazoDecidir[61] = { descCorta: 'EXCEDE LIMITE', desc: 'Denegada, excede límite remanente de la tarjeta.'};
erroresRechazoDecidir[65] = { descCorta: 'EXCEDE LIM. TARJETA', desc: 'Denegada, excede límite remanente de la tarjeta'};
erroresRechazoDecidir[76] = { descCorta: 'LLAMAR AL EMISOR', desc: 'Solicitar autorización telefónica, en caso de ser aprobada, cargar el código obtenido y dejar la operación en'};
erroresRechazoDecidir[77] = { descCorta: 'ERROR PLAN/CUOTAS', desc: 'Denegada, cantidad de cuotas inválida para el plan seleccionado.'};
erroresRechazoDecidir[89] = { descCorta: 'TERMINAL INVALIDA', desc: 'Denegada, número de terminal no habilitado por el Emisor.'};
erroresRechazoDecidir[91] = { descCorta: 'EMISOR FUERA LINEA', desc: 'Solicitar autorización telefónica, en caso de ser aprobada, cargar el código obtenido y dejar la operación en'};
erroresRechazoDecidir[94] = { descCorta: 'NRO. SEC. DUPLICAD', desc: 'Denegada. Error en mensaje. Envíe nuevamente la transacción incrementando en uno el system trace de la misma'};
erroresRechazoDecidir[95] = { descCorta: 'RE-TRANSMITIENDO', desc: 'Diferencias en la conciliación del cierre, envíe Batch Upload.'};
erroresRechazoDecidir[96] = { descCorta: 'ERROR EN SISTEMA', desc: 'Mal funcionamiento del sistema. Solicitar autorización telefónica.'};
erroresRechazoDecidir[97] = { descCorta: 'Error en sistema host', desc: 'Error en sistema host'};
erroresRechazoDecidir[98] = { descCorta: 'VER RECHAZO EN TICKET', desc: 'Deben imprimir la información Suministrada en el Campo ISO 63.'};

export const erroresMiddleware:any = [];
erroresMiddleware['vencimiento'] = { desc: 'El pago está vencido'};
erroresMiddleware['notificado'] = { desc: 'El pago ya fue completado/cancelado y se notificó'};
erroresMiddleware['url'] = { desc: 'Url invalido'};

